function odometry_ts = get_odometry_timeseries(bag_obj, full_topic_name)
% GET_ODOMETRY_TIMESERIES Return timeseries of standard nav_msgs/Odometry ROS message
% odometry_ts = get_odometry_timeseries(bag_obj, '/odometry') creates
% timeseries from topic '/odometry' from BagSelection object
% odometry_ts columns contain, in the order, position.x, position.y,
% position.z, orientation.x, orientation.y, orientation.z, orientation.w

odometry_selector = select(bag_obj, 'Topic', full_topic_name);

odometry_ts = timeseries(odometry_selector, ...
                      'Pose.Pose.Position.X', ...
                      'Pose.Pose.Position.Y', ...
                      'Pose.Pose.Position.Z', ...
                      'Pose.Pose.Orientation.X', ...
                      'Pose.Pose.Orientation.Y', ...
                      'Pose.Pose.Orientation.Z', ...
                      'Pose.Pose.Orientation.W');
                                 
end

