function transform_ts = get_transform_stamped_timeseries(bag_obj, full_topic_name)
% GET_TRANSFORM_STAMPED_TIMESERIES Return timeseries of standard geometry_msgs/TrasformStamped ROS message
% transform_ts = get_transform_stamped_timeseries(bag_obj, '/transform_stamped') creates
% timeseries from topic '/transform_stamped' from BagSelection object
% transformation_ts columns contain, in the order, translation.x, translation.y,
% translation.z, rotation.x, rotation.y, rotation.z, rotation.w

transformation_selector = select(bag_obj, 'Topic', full_topic_name);

transform_ts = timeseries(transformation_selector, ...
                                'Transform.Translation.X', ...
                                'Transform.Translation.Y', ...
                                'Transform.Translation.Z', ...
                                'Transform.Rotation.X', ...
                                'Transform.Rotation.Y', ...
                                'Transform.Rotation.Z', ...
                                'Transform.Rotation.W');
                                 
end

